-- Rewritten kana mnemonics: every hint pairs the shape of the character with a
-- keyword that starts with its actual reading, so recalling the picture gives the sound.
-- Look-alike kana carry a short note telling them apart.
-- Run this against the database to update characters that are already seeded.

-- Hiragana mnemonics (71)
UPDATE japanese_characters SET "mnemonicHint" = '🅰️ A capital A with a curl tied on — an ant hauling an apple. Say ''ah''.' WHERE character = 'あ';
UPDATE japanese_characters SET "mnemonicHint" = '🐟 Two eels swimming side by side — ''ee'' as in eel.' WHERE character = 'い';
UPDATE japanese_characters SET "mnemonicHint" = '🙇 A person hunched under a heavy load, groaning ''ooo''.' WHERE character = 'う';
UPDATE japanese_characters SET "mnemonicHint" = '🦢 An exotic bird standing tall with one fancy tail feather — ''e'' for exotic.' WHERE character = 'え';
UPDATE japanese_characters SET "mnemonicHint" = '⛳ A golfer mid-swing beside the flag — the ball sails off and everyone yells ''Oh!'' (あ has no dangling foot.)' WHERE character = 'お';
UPDATE japanese_characters SET "mnemonicHint" = '🗡️ A katana with its handle crossing the blade — ''ka'' for katana.' WHERE character = 'か';
UPDATE japanese_characters SET "mnemonicHint" = '🔑 An old key with two teeth on the stem — ''ki'' is literally ''key''.' WHERE character = 'き';
UPDATE japanese_characters SET "mnemonicHint" = '🐦 A cuckoo bird''s open beak, calling ''ku-ku''.' WHERE character = 'く';
UPDATE japanese_characters SET "mnemonicHint" = '🍺 A beer keg with the tap sticking out the side — ''ke'' for keg.' WHERE character = 'け';
UPDATE japanese_characters SET "mnemonicHint" = '🐟 Two koi swimming one above the other — ''ko'' for koi.' WHERE character = 'こ';
UPDATE japanese_characters SET "mnemonicHint" = '🍶 A bottle tipping to pour sake into a cup — ''sa'' for sake. (ち is its mirror image.)' WHERE character = 'さ';
UPDATE japanese_characters SET "mnemonicHint" = '🎣 One long fishing line dangling in the water — she is patiently waiting. ''shi'' sounds like ''she''.' WHERE character = 'し';
UPDATE japanese_characters SET "mnemonicHint" = '🍣 A sushi roll skewered on a stick — ''su'' for sushi.' WHERE character = 'す';
UPDATE japanese_characters SET "mnemonicHint" = '🤳 A face made of strokes: two eyes, a nose, and a wide grin — say ''seh'' for the selfie.' WHERE character = 'せ';
UPDATE japanese_characters SET "mnemonicHint" = '🧵 A zig-zag of thread coming off a sewing machine — ''so'' for sewing.' WHERE character = 'そ';
UPDATE japanese_characters SET "mnemonicHint" = '🌮 A fork on the left, a taco on the right — ''ta'' for taco.' WHERE character = 'た';
UPDATE japanese_characters SET "mnemonicHint" = '📣 A cheerleader mid-jump, ponytail flying — ''chi'' for cheer. (Mirror image of さ.)' WHERE character = 'ち';
UPDATE japanese_characters SET "mnemonicHint" = '🌊 One curling wave about to break — ''tsu'' for tsunami.' WHERE character = 'つ';
UPDATE japanese_characters SET "mnemonicHint" = '🐕 A dog''s tail curling up as it wags — ''te'' for tail.' WHERE character = 'て';
UPDATE japanese_characters SET "mnemonicHint" = '🦶 A toe with a thorn stuck in the side — ouch! ''to'' for toe.' WHERE character = 'と';
UPDATE japanese_characters SET "mnemonicHint" = '⛪ A nun kneeling beside a cross — ''na'' for nun.' WHERE character = 'な';
UPDATE japanese_characters SET "mnemonicHint" = '🦵 Someone kneeling: straight back, bent knees — ''ni'' for knee.' WHERE character = 'に';
UPDATE japanese_characters SET "mnemonicHint" = '🍜 Chopsticks lifting a loop of noodles — ''nu'' for noodles. (め has no loop.)' WHERE character = 'ぬ';
UPDATE japanese_characters SET "mnemonicHint" = '🐱 A cat sitting with its tail curled into a spiral — cat is ''neko''. ''ne''.' WHERE character = 'ね';
UPDATE japanese_characters SET "mnemonicHint" = '🚭 The circle-and-slash of a no-smoking sign — ''no'' means no.' WHERE character = 'の';
UPDATE japanese_characters SET "mnemonicHint" = '🏠 A house with a chimney, where you laugh ''ha ha'' with the door shut.' WHERE character = 'は';
UPDATE japanese_characters SET "mnemonicHint" = '😄 A wide grin seen from the side, laughing ''hee hee'' — ''hi'' sounds like ''hee''.' WHERE character = 'ひ';
UPDATE japanese_characters SET "mnemonicHint" = '🗻 Mount Fuji with a cloud on either side — ''fu'' for Fuji.' WHERE character = 'ふ';
UPDATE japanese_characters SET "mnemonicHint" = '🌾 A haystack sitting in a field — ''heh'' for haystack.' WHERE character = 'へ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 The は house plus an antenna bar on the roof — now it''s a proper home. ''ho''.' WHERE character = 'ほ';
UPDATE japanese_characters SET "mnemonicHint" = '👩 Mama with her hair in a bun and her arms folded — ''ma'' for mama.' WHERE character = 'ま';
UPDATE japanese_characters SET "mnemonicHint" = '🎶 A curly 21 that doubles as a music note — sing do-re-MI.' WHERE character = 'み';
UPDATE japanese_characters SET "mnemonicHint" = '🐄 A cow''s face with a snout and a tuft of hair — ''mu'' for moo.' WHERE character = 'む';
UPDATE japanese_characters SET "mnemonicHint" = '👁️ An eye with one long lash and no loop on the end — ''me'' (目) means eye. (ぬ is the one with the loop.)' WHERE character = 'め';
UPDATE japanese_characters SET "mnemonicHint" = '🎣 A hook with two worms on it — you want more fish. ''mo'' for more.' WHERE character = 'も';
UPDATE japanese_characters SET "mnemonicHint" = '⛵ A yacht''s sail leaning into the breeze — ''ya'' for yacht.' WHERE character = 'や';
UPDATE japanese_characters SET "mnemonicHint" = '🐡 A strange fish with a curled tail — ''yu'' sounds like ''you'': there''s no fish quite like you.' WHERE character = 'ゆ';
UPDATE japanese_characters SET "mnemonicHint" = '🪀 A yo-yo hanging off its string — ''yo'' for yo-yo.' WHERE character = 'よ';
UPDATE japanese_characters SET "mnemonicHint" = '🐰 A rabbit sitting up with one ear flopped over — ''ra'' for rabbit.' WHERE character = 'ら';
UPDATE japanese_characters SET "mnemonicHint" = '🎋 Two reeds standing in the shallows of a river — ''ri'' for reeds.' WHERE character = 'り';
UPDATE japanese_characters SET "mnemonicHint" = '🔁 A route that ends in a loop — ''ru'' for route. (ろ has no loop.)' WHERE character = 'る';
UPDATE japanese_characters SET "mnemonicHint" = '🧘 A person leaning back to rest — ''re'' for rest.' WHERE character = 'れ';
UPDATE japanese_characters SET "mnemonicHint" = '🛣️ A road with one sharp bend and no loop at the end — ''ro'' for road. (る is the looped one.)' WHERE character = 'ろ';
UPDATE japanese_characters SET "mnemonicHint" = '🌊 A wave curling over at the corner — ''wa'' for wave. (ね''s tail spirals, れ''s kicks out.)' WHERE character = 'わ';
UPDATE japanese_characters SET "mnemonicHint" = '🌪️ A person blown over by a whirlwind — said ''o'', and only ever used as the object particle.' WHERE character = 'を';
UPDATE japanese_characters SET "mnemonicHint" = '✍️ One loose squiggle, like a cursive n — the only kana that''s a consonant all by itself.' WHERE character = 'ん';
UPDATE japanese_characters SET "mnemonicHint" = '🗡️ ゛ The か katana plus two ticks — voice the k and it clangs into ''ga''.' WHERE character = 'が';
UPDATE japanese_characters SET "mnemonicHint" = '🔑 ゛ The き key plus two ticks — the k voices into ''gi''.' WHERE character = 'ぎ';
UPDATE japanese_characters SET "mnemonicHint" = '🐦 ゛ The く cuckoo plus two ticks — the k voices into ''gu''.' WHERE character = 'ぐ';
UPDATE japanese_characters SET "mnemonicHint" = '🍺 ゛ The け keg plus two ticks — the k voices into ''ge''.' WHERE character = 'げ';
UPDATE japanese_characters SET "mnemonicHint" = '🐟 ゛ The こ koi plus two ticks — the k voices into ''go''.' WHERE character = 'ご';
UPDATE japanese_characters SET "mnemonicHint" = '🍶 ゛ The さ sake bottle plus two ticks — the s voices into ''za''.' WHERE character = 'ざ';
UPDATE japanese_characters SET "mnemonicHint" = '🎣 ゛ The し fishing line plus two ticks — ''shi'' voices into ''ji''.' WHERE character = 'じ';
UPDATE japanese_characters SET "mnemonicHint" = '🍣 ゛ The す sushi roll plus two ticks — the s voices into ''zu''.' WHERE character = 'ず';
UPDATE japanese_characters SET "mnemonicHint" = '🤳 ゛ The せ selfie face plus two ticks — the s voices into ''ze''.' WHERE character = 'ぜ';
UPDATE japanese_characters SET "mnemonicHint" = '🧵 ゛ The そ sewing thread plus two ticks — the s voices into ''zo''.' WHERE character = 'ぞ';
UPDATE japanese_characters SET "mnemonicHint" = '🌮 ゛ The た taco plus two ticks — the t voices into ''da''.' WHERE character = 'だ';
UPDATE japanese_characters SET "mnemonicHint" = '📣 ゛ The ち cheerleader plus two ticks — rare, and said exactly like じ.' WHERE character = 'ぢ';
UPDATE japanese_characters SET "mnemonicHint" = '🌊 ゛ The つ wave plus two ticks — rare, and said exactly like ず.' WHERE character = 'づ';
UPDATE japanese_characters SET "mnemonicHint" = '🐕 ゛ The て wagging tail plus two ticks — the t voices into ''de''.' WHERE character = 'で';
UPDATE japanese_characters SET "mnemonicHint" = '🦶 ゛ The と stubbed toe plus two ticks — the t voices into ''do''.' WHERE character = 'ど';
UPDATE japanese_characters SET "mnemonicHint" = '🏠 ゛ The は house plus two ticks — the h voices into ''ba''.' WHERE character = 'ば';
UPDATE japanese_characters SET "mnemonicHint" = '😄 ゛ The ひ grin plus two ticks — the h voices into ''bi''.' WHERE character = 'び';
UPDATE japanese_characters SET "mnemonicHint" = '🗻 ゛ Mount Fuji ふ plus two ticks — the h voices into ''bu''.' WHERE character = 'ぶ';
UPDATE japanese_characters SET "mnemonicHint" = '🌾 ゛ The へ haystack plus two ticks — the h voices into ''be''.' WHERE character = 'べ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 ゛ The ほ home plus two ticks — the h voices into ''bo''.' WHERE character = 'ぼ';
UPDATE japanese_characters SET "mnemonicHint" = '🏠 ゜ The は house plus a small circle — the circle pops the sound into ''pa''.' WHERE character = 'ぱ';
UPDATE japanese_characters SET "mnemonicHint" = '😄 ゜ The ひ grin plus a small circle — it pops into ''pi''.' WHERE character = 'ぴ';
UPDATE japanese_characters SET "mnemonicHint" = '🗻 ゜ Mount Fuji ふ plus a small circle — it pops into ''pu''.' WHERE character = 'ぷ';
UPDATE japanese_characters SET "mnemonicHint" = '🌾 ゜ The へ haystack plus a small circle — it pops into ''pe''.' WHERE character = 'ぺ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 ゜ The ほ home plus a small circle — it pops into ''po''.' WHERE character = 'ぽ';

-- Katakana mnemonics (69)
UPDATE japanese_characters SET "mnemonicHint" = '🪓 An axe with the blade angled off the top — ''a'' for axe. (All corners; あ is the loopy one.)' WHERE character = 'ア';
UPDATE japanese_characters SET "mnemonicHint" = '🦅 An eagle diving with one wing thrown out — ''ee'' for eagle.' WHERE character = 'イ';
UPDATE japanese_characters SET "mnemonicHint" = '🙇 The う person bowing, now with a roof for a hat — still groaning ''ooo''.' WHERE character = 'ウ';
UPDATE japanese_characters SET "mnemonicHint" = '🏗️ A steel I-beam seen end-on — what an engineer builds with. ''e''.' WHERE character = 'エ';
UPDATE japanese_characters SET "mnemonicHint" = '⛳ The same golf swing as お, drawn with straight lines — ''Oh!'' goes the ball.' WHERE character = 'オ';
UPDATE japanese_characters SET "mnemonicHint" = '🗡️ The か katana with one stroke fewer — ''ka'' for katana.' WHERE character = 'カ';
UPDATE japanese_characters SET "mnemonicHint" = '🔑 A key with two teeth — the top half of き. ''ki'' = key.' WHERE character = 'キ';
UPDATE japanese_characters SET "mnemonicHint" = '🐦 The く cuckoo''s open beak, sharpened into two strokes — ''ku''.' WHERE character = 'ク';
UPDATE japanese_characters SET "mnemonicHint" = '🍺 A keg tipped over on its side — ''ke'' for keg, same as け.' WHERE character = 'ケ';
UPDATE japanese_characters SET "mnemonicHint" = '🐟 Two koi swimming, drawn as a square bracket — ''ko'' for koi.' WHERE character = 'コ';
UPDATE japanese_characters SET "mnemonicHint" = '🍶 A sake bottle and two cups lined up on the bar — ''sa'' for sake.' WHERE character = 'サ';
UPDATE japanese_characters SET "mnemonicHint" = '😀 A smiley tipped on its side: two eyes and a wide smile, all running sideways. ''shi'' — she''s smiling. (ツ points down.)' WHERE character = 'シ';
UPDATE japanese_characters SET "mnemonicHint" = '🦸 Superman''s suit hanging empty on a hook — where did he go? ''su'' for suit.' WHERE character = 'ス';
UPDATE japanese_characters SET "mnemonicHint" = '🤳 The same selfie face as せ, squared off — ''se''.' WHERE character = 'セ';
UPDATE japanese_characters SET "mnemonicHint" = '🧵 One needle stabbing straight down, thread trailing — sewing. Strokes point down. (ン runs sideways.)' WHERE character = 'ソ';
UPDATE japanese_characters SET "mnemonicHint" = '🌮 A taco with a fold on the left — ''ta'' for taco, same as た.' WHERE character = 'タ';
UPDATE japanese_characters SET "mnemonicHint" = '📣 A cheerleader with pom-poms raised — ''chi'' for cheer, same as ち.' WHERE character = 'チ';
UPDATE japanese_characters SET "mnemonicHint" = '🌊 Two drops falling and a wave crashing down — ''tsu'' for tsunami. (シ''s strokes run sideways.)' WHERE character = 'ツ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 A telephone pole with two crossbars — ''te'' for telephone.' WHERE character = 'テ';
UPDATE japanese_characters SET "mnemonicHint" = '🦶 A toe with a thorn stuck in the side — ''to'' for toe, same as と.' WHERE character = 'ト';
UPDATE japanese_characters SET "mnemonicHint" = '⛪ The nun''s cross from な with the nun gone — just the cross is left. ''na'' for nun.' WHERE character = 'ナ';
UPDATE japanese_characters SET "mnemonicHint" = '2️⃣ Two flat lines — and ''ni'' (二) is the Japanese word for two.' WHERE character = 'ニ';
UPDATE japanese_characters SET "mnemonicHint" = '🍜 Chopsticks pulling noodles out of the bowl — ''nu'' for noodles, the angular ぬ.' WHERE character = 'ヌ';
UPDATE japanese_characters SET "mnemonicHint" = '👔 A necktie hanging with the knot at the top — ''ne'' for necktie.' WHERE character = 'ネ';
UPDATE japanese_characters SET "mnemonicHint" = '🚭 The slash off the no-smoking sign, all on its own — ''no''.' WHERE character = 'ノ';
UPDATE japanese_characters SET "mnemonicHint" = '😂 Two strokes bursting apart like a mouth open wide: ''ha ha!''' WHERE character = 'ハ';
UPDATE japanese_characters SET "mnemonicHint" = '😄 A person grinning from the side, laughing ''hee hee'' — same face as ひ.' WHERE character = 'ヒ';
UPDATE japanese_characters SET "mnemonicHint" = '🗻 One slope of Mount Fuji — just the left side of the mountain. ''fu'' for Fuji.' WHERE character = 'フ';
UPDATE japanese_characters SET "mnemonicHint" = '🌾 The same haystack as hiragana へ — identical shape, identical sound.' WHERE character = 'ヘ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 The ほ home with its roof antenna, squared off — ''ho''.' WHERE character = 'ホ';
UPDATE japanese_characters SET "mnemonicHint" = '👩 Mama with her arms folded over — ''ma'' for mama, same as ま.' WHERE character = 'マ';
UPDATE japanese_characters SET "mnemonicHint" = '🎶 Three strings you strum for do-re-MI — ''mi''.' WHERE character = 'ミ';
UPDATE japanese_characters SET "mnemonicHint" = '🐄 A cow''s snout seen head-on — ''mu'' for moo, same as む.' WHERE character = 'ム';
UPDATE japanese_characters SET "mnemonicHint" = '🏥 A medical cross tipped onto its side — ''me'' for medical. (It''s also 目 ''me'', eye, with an X through it.)' WHERE character = 'メ';
UPDATE japanese_characters SET "mnemonicHint" = '🎣 The も fishhook straightened out — you still want more fish. ''mo''.' WHERE character = 'モ';
UPDATE japanese_characters SET "mnemonicHint" = '⛵ A yacht''s mast and sail leaning in the breeze — ''ya'' for yacht.' WHERE character = 'ヤ';
UPDATE japanese_characters SET "mnemonicHint" = '🔤 Give it a quarter turn and there''s a capital U — ''yu''. (コ stays a bracket however you turn it.)' WHERE character = 'ユ';
UPDATE japanese_characters SET "mnemonicHint" = '🪀 A yo-yo''s spool seen edge-on, three prongs — ''yo'' for yo-yo.' WHERE character = 'ヨ';
UPDATE japanese_characters SET "mnemonicHint" = '🐰 The ら rabbit, ear flopped, in two clean strokes — ''ra'' for rabbit.' WHERE character = 'ラ';
UPDATE japanese_characters SET "mnemonicHint" = '🎋 Two reeds standing in the water — ''ri'' for reeds, same as り.' WHERE character = 'リ';
UPDATE japanese_characters SET "mnemonicHint" = '🛣️ Two routes forking apart, the right one curling away — ''ru'' for route.' WHERE character = 'ル';
UPDATE japanese_characters SET "mnemonicHint" = '✔️ A tick mark leaning back to rest — ''re'' for rest, same as れ.' WHERE character = 'レ';
UPDATE japanese_characters SET "mnemonicHint" = '🛣️ A road looping one square block, ending where it started — ''ro'' for road.' WHERE character = 'ロ';
UPDATE japanese_characters SET "mnemonicHint" = '🌊 A wave curling over the corner — ''wa'' for wave. (ウ wears a hat; ク is missing the left leg.)' WHERE character = 'ワ';
UPDATE japanese_characters SET "mnemonicHint" = '🌪️ ワ with a bar driven through it — the を whirlwind, squared off. Barely ever written.' WHERE character = 'ヲ';
UPDATE japanese_characters SET "mnemonicHint" = '✍️ One flick and a dot, both running sideways like シ — just ''n''. (ソ points down.)' WHERE character = 'ン';
UPDATE japanese_characters SET "mnemonicHint" = '🗡️ ゛ The カ katana plus two ticks — the k voices into ''ga''.' WHERE character = 'ガ';
UPDATE japanese_characters SET "mnemonicHint" = '🔑 ゛ The キ key plus two ticks — the k voices into ''gi''.' WHERE character = 'ギ';
UPDATE japanese_characters SET "mnemonicHint" = '🐦 ゛ The ク cuckoo beak plus two ticks — the k voices into ''gu''.' WHERE character = 'グ';
UPDATE japanese_characters SET "mnemonicHint" = '🍺 ゛ The ケ keg plus two ticks — the k voices into ''ge''.' WHERE character = 'ゲ';
UPDATE japanese_characters SET "mnemonicHint" = '🐟 ゛ The コ koi plus two ticks — the k voices into ''go''.' WHERE character = 'ゴ';
UPDATE japanese_characters SET "mnemonicHint" = '🍶 ゛ The サ sake bottle plus two ticks — the s voices into ''za''.' WHERE character = 'ザ';
UPDATE japanese_characters SET "mnemonicHint" = '😀 ゛ The シ sideways smile plus two ticks — ''shi'' voices into ''ji''.' WHERE character = 'ジ';
UPDATE japanese_characters SET "mnemonicHint" = '🦸 ゛ The ス empty suit plus two ticks — the s voices into ''zu''.' WHERE character = 'ズ';
UPDATE japanese_characters SET "mnemonicHint" = '🤳 ゛ The セ selfie face plus two ticks — the s voices into ''ze''.' WHERE character = 'ゼ';
UPDATE japanese_characters SET "mnemonicHint" = '🧵 ゛ The ソ sewing needle plus two ticks — the s voices into ''zo''.' WHERE character = 'ゾ';
UPDATE japanese_characters SET "mnemonicHint" = '🌮 ゛ The タ taco plus two ticks — the t voices into ''da''.' WHERE character = 'ダ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 ゛ The テ telephone pole plus two ticks — the t voices into ''de''.' WHERE character = 'デ';
UPDATE japanese_characters SET "mnemonicHint" = '🦶 ゛ The ト stubbed toe plus two ticks — the t voices into ''do''.' WHERE character = 'ド';
UPDATE japanese_characters SET "mnemonicHint" = '😂 ゛ The ハ laugh plus two ticks — the h voices into ''ba''.' WHERE character = 'バ';
UPDATE japanese_characters SET "mnemonicHint" = '😄 ゛ The ヒ grin plus two ticks — the h voices into ''bi''.' WHERE character = 'ビ';
UPDATE japanese_characters SET "mnemonicHint" = '🗻 ゛ The フ Fuji slope plus two ticks — the h voices into ''bu''.' WHERE character = 'ブ';
UPDATE japanese_characters SET "mnemonicHint" = '🌾 ゛ The ヘ haystack plus two ticks — the h voices into ''be''.' WHERE character = 'ベ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 ゛ The ホ home plus two ticks — the h voices into ''bo''.' WHERE character = 'ボ';
UPDATE japanese_characters SET "mnemonicHint" = '😂 ゜ The ハ laugh plus a small circle — the circle pops it into ''pa''.' WHERE character = 'パ';
UPDATE japanese_characters SET "mnemonicHint" = '😄 ゜ The ヒ grin plus a small circle — it pops into ''pi''.' WHERE character = 'ピ';
UPDATE japanese_characters SET "mnemonicHint" = '🗻 ゜ The フ Fuji slope plus a small circle — it pops into ''pu''.' WHERE character = 'プ';
UPDATE japanese_characters SET "mnemonicHint" = '🌾 ゜ The ヘ haystack plus a small circle — it pops into ''pe''.' WHERE character = 'ペ';
UPDATE japanese_characters SET "mnemonicHint" = '📡 ゜ The ホ home plus a small circle — it pops into ''po''.' WHERE character = 'ポ';
