-- Backfill common example words for kanji (50)
UPDATE kanji SET "exampleWords" = '[{"word":"日本","reading":"にほん","meaning":"Japan"},{"word":"今日","reading":"きょう","meaning":"today"},{"word":"毎日","reading":"まいにち","meaning":"every day"}]'::jsonb WHERE character = '日';
UPDATE kanji SET "exampleWords" = '[{"word":"月曜日","reading":"げつようび","meaning":"Monday"},{"word":"今月","reading":"こんげつ","meaning":"this month"}]'::jsonb WHERE character = '月';
UPDATE kanji SET "exampleWords" = '[{"word":"火曜日","reading":"かようび","meaning":"Tuesday"},{"word":"花火","reading":"はなび","meaning":"fireworks"}]'::jsonb WHERE character = '火';
UPDATE kanji SET "exampleWords" = '[{"word":"水曜日","reading":"すいようび","meaning":"Wednesday"},{"word":"水泳","reading":"すいえい","meaning":"swimming"}]'::jsonb WHERE character = '水';
UPDATE kanji SET "exampleWords" = '[{"word":"木曜日","reading":"もくようび","meaning":"Thursday"},{"word":"木材","reading":"もくざい","meaning":"lumber, wood"}]'::jsonb WHERE character = '木';
UPDATE kanji SET "exampleWords" = '[{"word":"金曜日","reading":"きんようび","meaning":"Friday"},{"word":"お金","reading":"おかね","meaning":"money"}]'::jsonb WHERE character = '金';
UPDATE kanji SET "exampleWords" = '[{"word":"土曜日","reading":"どようび","meaning":"Saturday"},{"word":"土地","reading":"とち","meaning":"land"}]'::jsonb WHERE character = '土';
UPDATE kanji SET "exampleWords" = '[{"word":"富士山","reading":"ふじさん","meaning":"Mt. Fuji"},{"word":"山道","reading":"やまみち","meaning":"mountain path"}]'::jsonb WHERE character = '山';
UPDATE kanji SET "exampleWords" = '[{"word":"川岸","reading":"かわぎし","meaning":"riverbank"},{"word":"小川","reading":"おがわ","meaning":"stream"}]'::jsonb WHERE character = '川';
UPDATE kanji SET "exampleWords" = '[{"word":"日本人","reading":"にほんじん","meaning":"Japanese person"},{"word":"大人","reading":"おとな","meaning":"adult"}]'::jsonb WHERE character = '人';
UPDATE kanji SET "exampleWords" = '[{"word":"入口","reading":"いりぐち","meaning":"entrance"},{"word":"出口","reading":"でぐち","meaning":"exit"}]'::jsonb WHERE character = '口';
UPDATE kanji SET "exampleWords" = '[{"word":"手紙","reading":"てがみ","meaning":"letter"},{"word":"上手","reading":"じょうず","meaning":"skillful"}]'::jsonb WHERE character = '手';
UPDATE kanji SET "exampleWords" = '[{"word":"目的","reading":"もくてき","meaning":"purpose, goal"},{"word":"目玉","reading":"めだま","meaning":"eyeball"}]'::jsonb WHERE character = '目';
UPDATE kanji SET "exampleWords" = '[{"word":"耳鼻科","reading":"じびか","meaning":"ENT clinic"},{"word":"早耳","reading":"はやみみ","meaning":"quick to hear news"}]'::jsonb WHERE character = '耳';
UPDATE kanji SET "exampleWords" = '[{"word":"満足","reading":"まんぞく","meaning":"satisfaction"},{"word":"足音","reading":"あしおと","meaning":"footstep sound"}]'::jsonb WHERE character = '足';
UPDATE kanji SET "exampleWords" = '[{"word":"一番","reading":"いちばん","meaning":"number one, best"},{"word":"一日","reading":"いちにち","meaning":"one day"}]'::jsonb WHERE character = '一';
UPDATE kanji SET "exampleWords" = '[{"word":"二人","reading":"ふたり","meaning":"two people"},{"word":"二月","reading":"にがつ","meaning":"February"}]'::jsonb WHERE character = '二';
UPDATE kanji SET "exampleWords" = '[{"word":"三人","reading":"さんにん","meaning":"three people"},{"word":"三月","reading":"さんがつ","meaning":"March"}]'::jsonb WHERE character = '三';
UPDATE kanji SET "exampleWords" = '[{"word":"四月","reading":"しがつ","meaning":"April"},{"word":"四季","reading":"しき","meaning":"four seasons"}]'::jsonb WHERE character = '四';
UPDATE kanji SET "exampleWords" = '[{"word":"五月","reading":"ごがつ","meaning":"May"},{"word":"五人","reading":"ごにん","meaning":"five people"}]'::jsonb WHERE character = '五';
UPDATE kanji SET "exampleWords" = '[{"word":"六月","reading":"ろくがつ","meaning":"June"},{"word":"六時","reading":"ろくじ","meaning":"six o''clock"}]'::jsonb WHERE character = '六';
UPDATE kanji SET "exampleWords" = '[{"word":"七月","reading":"しちがつ","meaning":"July"},{"word":"七五三","reading":"しちごさん","meaning":"Shichi-Go-San festival"}]'::jsonb WHERE character = '七';
UPDATE kanji SET "exampleWords" = '[{"word":"八月","reading":"はちがつ","meaning":"August"},{"word":"八百屋","reading":"やおや","meaning":"greengrocer"}]'::jsonb WHERE character = '八';
UPDATE kanji SET "exampleWords" = '[{"word":"九月","reading":"くがつ","meaning":"September"},{"word":"九州","reading":"きゅうしゅう","meaning":"Kyushu"}]'::jsonb WHERE character = '九';
UPDATE kanji SET "exampleWords" = '[{"word":"十月","reading":"じゅうがつ","meaning":"October"},{"word":"十分","reading":"じゅうぶん","meaning":"enough, sufficient"}]'::jsonb WHERE character = '十';
UPDATE kanji SET "exampleWords" = '[{"word":"百円","reading":"ひゃくえん","meaning":"100 yen"},{"word":"百科事典","reading":"ひゃっかじてん","meaning":"encyclopedia"}]'::jsonb WHERE character = '百';
UPDATE kanji SET "exampleWords" = '[{"word":"千円","reading":"せんえん","meaning":"1000 yen"},{"word":"千葉","reading":"ちば","meaning":"Chiba (place name)"}]'::jsonb WHERE character = '千';
UPDATE kanji SET "exampleWords" = '[{"word":"万年筆","reading":"まんねんひつ","meaning":"fountain pen"},{"word":"万一","reading":"まんいち","meaning":"just in case"}]'::jsonb WHERE character = '万';
UPDATE kanji SET "exampleWords" = '[{"word":"上手","reading":"じょうず","meaning":"skillful"},{"word":"上着","reading":"うわぎ","meaning":"jacket"}]'::jsonb WHERE character = '上';
UPDATE kanji SET "exampleWords" = '[{"word":"下着","reading":"したぎ","meaning":"underwear"},{"word":"地下","reading":"ちか","meaning":"underground"}]'::jsonb WHERE character = '下';
UPDATE kanji SET "exampleWords" = '[{"word":"中心","reading":"ちゅうしん","meaning":"center"},{"word":"中学校","reading":"ちゅうがっこう","meaning":"middle school"}]'::jsonb WHERE character = '中';
UPDATE kanji SET "exampleWords" = '[{"word":"大学","reading":"だいがく","meaning":"university"},{"word":"大人","reading":"おとな","meaning":"adult"}]'::jsonb WHERE character = '大';
UPDATE kanji SET "exampleWords" = '[{"word":"小学校","reading":"しょうがっこう","meaning":"elementary school"},{"word":"小さい","reading":"ちいさい","meaning":"small"}]'::jsonb WHERE character = '小';
UPDATE kanji SET "exampleWords" = '[{"word":"今年","reading":"ことし","meaning":"this year"},{"word":"去年","reading":"きょねん","meaning":"last year"}]'::jsonb WHERE character = '年';
UPDATE kanji SET "exampleWords" = '[{"word":"外国","reading":"がいこく","meaning":"foreign country"},{"word":"国語","reading":"こくご","meaning":"national language"}]'::jsonb WHERE character = '国';
UPDATE kanji SET "exampleWords" = '[{"word":"日本語","reading":"にほんご","meaning":"Japanese language"},{"word":"英語","reading":"えいご","meaning":"English language"}]'::jsonb WHERE character = '語';
UPDATE kanji SET "exampleWords" = '[{"word":"本当","reading":"ほんとう","meaning":"true, really"},{"word":"本屋","reading":"ほんや","meaning":"bookstore"}]'::jsonb WHERE character = '本';
UPDATE kanji SET "exampleWords" = '[{"word":"学校","reading":"がっこう","meaning":"school"},{"word":"学生","reading":"がくせい","meaning":"student"}]'::jsonb WHERE character = '学';
UPDATE kanji SET "exampleWords" = '[{"word":"学校","reading":"がっこう","meaning":"school"},{"word":"校長","reading":"こうちょう","meaning":"principal"}]'::jsonb WHERE character = '校';
UPDATE kanji SET "exampleWords" = '[{"word":"先生","reading":"せんせい","meaning":"teacher"},{"word":"先週","reading":"せんしゅう","meaning":"last week"}]'::jsonb WHERE character = '先';
UPDATE kanji SET "exampleWords" = '[{"word":"先生","reading":"せんせい","meaning":"teacher"},{"word":"学生","reading":"がくせい","meaning":"student"}]'::jsonb WHERE character = '生';
UPDATE kanji SET "exampleWords" = '[{"word":"東京","reading":"とうきょう","meaning":"Tokyo"},{"word":"東口","reading":"ひがしぐち","meaning":"east exit"}]'::jsonb WHERE character = '東';
UPDATE kanji SET "exampleWords" = '[{"word":"西口","reading":"にしぐち","meaning":"west exit"},{"word":"関西","reading":"かんさい","meaning":"Kansai region"}]'::jsonb WHERE character = '西';
UPDATE kanji SET "exampleWords" = '[{"word":"南口","reading":"みなみぐち","meaning":"south exit"},{"word":"南極","reading":"なんきょく","meaning":"Antarctica"}]'::jsonb WHERE character = '南';
UPDATE kanji SET "exampleWords" = '[{"word":"北口","reading":"きたぐち","meaning":"north exit"},{"word":"北海道","reading":"ほっかいどう","meaning":"Hokkaido"}]'::jsonb WHERE character = '北';
UPDATE kanji SET "exampleWords" = '[{"word":"駅前","reading":"えきまえ","meaning":"in front of the station"},{"word":"東京駅","reading":"とうきょうえき","meaning":"Tokyo Station"}]'::jsonb WHERE character = '駅';
UPDATE kanji SET "exampleWords" = '[{"word":"電車","reading":"でんしゃ","meaning":"train"},{"word":"電話","reading":"でんわ","meaning":"telephone"}]'::jsonb WHERE character = '電';
UPDATE kanji SET "exampleWords" = '[{"word":"電車","reading":"でんしゃ","meaning":"train"},{"word":"自転車","reading":"じてんしゃ","meaning":"bicycle"}]'::jsonb WHERE character = '車';
UPDATE kanji SET "exampleWords" = '[{"word":"店員","reading":"てんいん","meaning":"shop clerk"},{"word":"売店","reading":"ばいてん","meaning":"kiosk, stand"}]'::jsonb WHERE character = '店';
UPDATE kanji SET "exampleWords" = '[{"word":"食べ物","reading":"たべもの","meaning":"food"},{"word":"食事","reading":"しょくじ","meaning":"meal"}]'::jsonb WHERE character = '食';
