-- Update mnemonic hints for all hiragana
UPDATE japanese_characters SET "mnemonicHint" = 'Looks like an ''a'' with a fishing hook tail — imagine catching an ''ah!'' fish.' WHERE character = 'あ';
UPDATE japanese_characters SET "mnemonicHint" = 'Two chopsticks standing side by side, like the two dots on a lowercase ''i''.' WHERE character = 'い';
UPDATE japanese_characters SET "mnemonicHint" = 'A bird''s beak dipping down to sip water — ''u'' for a sip of water.' WHERE character = 'う';
UPDATE japanese_characters SET "mnemonicHint" = 'A stretched-out figure leaning forward, like someone exercising and yelling ''eh!''' WHERE character = 'え';
UPDATE japanese_characters SET "mnemonicHint" = 'A person with a round belly and a topknot — ''o'' for an ''oh so round'' curve.' WHERE character = 'お';
UPDATE japanese_characters SET "mnemonicHint" = 'A knife slicing with a ''ka-ching'' sound as the blade swings down.' WHERE character = 'か';
UPDATE japanese_characters SET "mnemonicHint" = 'Looks like a key with two teeth on the stem — ''ki'' sounds like ''key''.' WHERE character = 'き';
UPDATE japanese_characters SET "mnemonicHint" = 'A boomerang shape curving back — ''ku'' curves like a comma.' WHERE character = 'く';
UPDATE japanese_characters SET "mnemonicHint" = 'A key sticking out of a lock, shaped like a ''k'' with an extra leg.' WHERE character = 'け';
UPDATE japanese_characters SET "mnemonicHint" = 'Two parallel strokes stacked like two commas — ''ko-ko'' for ''comma-comma''.' WHERE character = 'こ';
UPDATE japanese_characters SET "mnemonicHint" = 'A fishing rod with a hook — ''sa'' for the ''saw'' cutting the line free.' WHERE character = 'さ';
UPDATE japanese_characters SET "mnemonicHint" = 'A single curved fishhook, simple as a soft ''shh'' whispered.' WHERE character = 'し';
UPDATE japanese_characters SET "mnemonicHint" = 'A swirling straw sucking up a drink — ''su'' for ''suck''.' WHERE character = 'す';
UPDATE japanese_characters SET "mnemonicHint" = 'A seesaw shape tilting side to side — ''se'' for ''seesaw''.' WHERE character = 'せ';
UPDATE japanese_characters SET "mnemonicHint" = 'A zigzag lightning bolt — ''so'' surprising, like a shock.' WHERE character = 'そ';
UPDATE japanese_characters SET "mnemonicHint" = 'A person standing with arms out, shouting ''ta-da!''' WHERE character = 'た';
UPDATE japanese_characters SET "mnemonicHint" = 'A curled ribbon, like a cheerleader''s pom-pom for a ''chi-chi-chi'' cheer.' WHERE character = 'ち';
UPDATE japanese_characters SET "mnemonicHint" = 'A single cresting wave — ''tsu'' as in tsunami.' WHERE character = 'つ';
UPDATE japanese_characters SET "mnemonicHint" = 'A hand reaching out, shaped like a hook — ''te'' for a ''ten-tacle'' reaching.' WHERE character = 'て';
UPDATE japanese_characters SET "mnemonicHint" = 'A toe pointing forward, a simple hook and line — ''to'' for ''toe''.' WHERE character = 'と';
UPDATE japanese_characters SET "mnemonicHint" = 'A knot tangled like noodles — ''na'' for ''noodle''.' WHERE character = 'な';
UPDATE japanese_characters SET "mnemonicHint" = 'Two chopsticks and a needle side by side — ''ni'' for ''needle''.' WHERE character = 'に';
UPDATE japanese_characters SET "mnemonicHint" = 'A noodle with a loop tangled at the end — ''nu'' for a ''noodle knot''.' WHERE character = 'ぬ';
UPDATE japanese_characters SET "mnemonicHint" = 'A cat''s tail curling with a loop — ''ne'' sounds like ''neko'' (cat).' WHERE character = 'ね';
UPDATE japanese_characters SET "mnemonicHint" = 'A single spiral loop, drawn in one stroke — like writing ''no'' with a swirl.' WHERE character = 'の';
UPDATE japanese_characters SET "mnemonicHint" = 'A person laughing ''ha ha'' with arms raised.' WHERE character = 'は';
UPDATE japanese_characters SET "mnemonicHint" = 'A simple curved smile — ''hi'' for a happy wave hello.' WHERE character = 'ひ';
UPDATE japanese_characters SET "mnemonicHint" = 'Mount Fuji''s silhouette in three strokes — ''fu'' for Fuji.' WHERE character = 'ふ';
UPDATE japanese_characters SET "mnemonicHint" = 'A single upward slope like a small hill — ''he'' for a hill.' WHERE character = 'へ';
UPDATE japanese_characters SET "mnemonicHint" = 'A house with a chimney and a flag — ''ho'' for ''home''.' WHERE character = 'ほ';
UPDATE japanese_characters SET "mnemonicHint" = 'A mother rocking a loop like a cradle — ''ma'' for ''mama''.' WHERE character = 'ま';
UPDATE japanese_characters SET "mnemonicHint" = 'A curled fishing line with a loop — ''mi'' for a miniature swirl.' WHERE character = 'み';
UPDATE japanese_characters SET "mnemonicHint" = 'A cow''s face mooing — ''mu'' sounds like ''moo''.' WHERE character = 'む';
UPDATE japanese_characters SET "mnemonicHint" = 'An eye shape looking back at you — ''me'' means ''eye'' in Japanese.' WHERE character = 'め';
UPDATE japanese_characters SET "mnemonicHint" = 'A fishhook with an extra loop — ''mo'' for ''more'' hook.' WHERE character = 'も';
UPDATE japanese_characters SET "mnemonicHint" = 'A slingshot ''Y'' shape — ''ya'' as in yelling ''yah!''' WHERE character = 'や';
UPDATE japanese_characters SET "mnemonicHint" = 'A hook with a loop like a U-turn — ''yu'' sounds like ''you''.' WHERE character = 'ゆ';
UPDATE japanese_characters SET "mnemonicHint" = 'A fishhook with a little flag — ''yo!'' waving hello.' WHERE character = 'よ';
UPDATE japanese_characters SET "mnemonicHint" = 'A rabbit''s ear flopping over — ''ra'' for ''rabbit''.' WHERE character = 'ら';
UPDATE japanese_characters SET "mnemonicHint" = 'Two strokes leaning like chopsticks — ''ri'' for ''rice'' sticks.' WHERE character = 'り';
UPDATE japanese_characters SET "mnemonicHint" = 'A loop swirling like a whirlpool — ''ru'' for the swirl.' WHERE character = 'る';
UPDATE japanese_characters SET "mnemonicHint" = 'A person leaning back, relaxed — ''re'' for ''rest''.' WHERE character = 'れ';
UPDATE japanese_characters SET "mnemonicHint" = 'A rolled-up scroll — ''ro'' for ''roll''.' WHERE character = 'ろ';
UPDATE japanese_characters SET "mnemonicHint" = 'A wave rolling with a loop at the end — ''wa'' for ''water wave''.' WHERE character = 'わ';
UPDATE japanese_characters SET "mnemonicHint" = 'A fishhook with a flourish — rarely written, only used as the particle ''wo/o''.' WHERE character = 'を';
UPDATE japanese_characters SET "mnemonicHint" = 'A single hooked stroke — the only sound that''s just ''n'', hooked and alone.' WHERE character = 'ん';
UPDATE japanese_characters SET "mnemonicHint" = 'Same shape as か (ka) with two small strokes (゛) added — the knife now clangs ''ga''.' WHERE character = 'が';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as き (ki) plus dakuten marks — the key buzzes into ''gi''.' WHERE character = 'ぎ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as く (ku) plus dakuten marks — the boomerang hums ''gu''.' WHERE character = 'ぐ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as け (ke) plus dakuten marks — the key-in-lock clicks ''ge''.' WHERE character = 'げ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as こ (ko) plus dakuten marks — the two commas buzz into ''go''.' WHERE character = 'ご';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as さ (sa) plus dakuten marks — the fishing rod buzzes ''za''.' WHERE character = 'ざ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as し (shi) plus dakuten marks — the fishhook buzzes into ''ji''.' WHERE character = 'じ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as す (su) plus dakuten marks — the straw slurp buzzes ''zu''.' WHERE character = 'ず';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as せ (se) plus dakuten marks — the seesaw buzzes ''ze''.' WHERE character = 'ぜ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as そ (so) plus dakuten marks — the lightning bolt buzzes ''zo''.' WHERE character = 'ぞ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as た (ta) plus dakuten marks — ''ta-da!'' becomes a buzzing ''da''.' WHERE character = 'だ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ち (chi) plus dakuten marks — rare, and pronounced just like じ.' WHERE character = 'ぢ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as つ (tsu) plus dakuten marks — rare, and pronounced just like ず.' WHERE character = 'づ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as て (te) plus dakuten marks — the reaching hand buzzes ''de''.' WHERE character = 'で';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as と (to) plus dakuten marks — the toe stomps ''do''.' WHERE character = 'ど';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as は (ha) plus dakuten marks — the laugh buzzes into ''ba''.' WHERE character = 'ば';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ひ (hi) plus dakuten marks — the smile buzzes ''bi''.' WHERE character = 'び';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ふ (fu) plus dakuten marks — Mount Fuji buzzes ''bu''.' WHERE character = 'ぶ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as へ (he) plus dakuten marks — the small hill buzzes ''be''.' WHERE character = 'べ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ほ (ho) plus dakuten marks — the house buzzes ''bo''.' WHERE character = 'ぼ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as は (ha) with a small circle (゜) — the laugh pops crisply into ''pa''.' WHERE character = 'ぱ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ひ (hi) with a small circle (゜) — the smile pops into ''pi''.' WHERE character = 'ぴ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ふ (fu) with a small circle (゜) — Mount Fuji pops into ''pu''.' WHERE character = 'ぷ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as へ (he) with a small circle (゜) — the hill pops into ''pe''.' WHERE character = 'ぺ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ほ (ho) with a small circle (゜) — the house pops into ''po''.' WHERE character = 'ぽ';

-- Update mnemonic hints for all katakana
UPDATE japanese_characters SET "mnemonicHint" = 'Sharp and angular, like the horns of an antelope — ''A'' for antelope.' WHERE character = 'ア';
UPDATE japanese_characters SET "mnemonicHint" = 'Two straight strokes like a mustache — a simple ''i'' shape.' WHERE character = 'イ';
UPDATE japanese_characters SET "mnemonicHint" = 'A roof over a hooked stroke, like a rabbit''s ear peeking under a lid.' WHERE character = 'ウ';
UPDATE japanese_characters SET "mnemonicHint" = 'Looks like a capital ''E'' rotated — an elevator shaft with three floors.' WHERE character = 'エ';
UPDATE japanese_characters SET "mnemonicHint" = 'A person raising one arm and shouting ''oh!''' WHERE character = 'オ';
UPDATE japanese_characters SET "mnemonicHint" = 'A sharp karate chop, angular version of か.' WHERE character = 'カ';
UPDATE japanese_characters SET "mnemonicHint" = 'A key with jagged teeth, angular version of き.' WHERE character = 'キ';
UPDATE japanese_characters SET "mnemonicHint" = 'A comma-like hook — ''ku'' for a cool, quick chop.' WHERE character = 'ク';
UPDATE japanese_characters SET "mnemonicHint" = 'A key with an extra leg, angular version of け.' WHERE character = 'ケ';
UPDATE japanese_characters SET "mnemonicHint" = 'A squared-off ''C'' shape, like a comma boxed in.' WHERE character = 'コ';
UPDATE japanese_characters SET "mnemonicHint" = 'A saw blade, angular version of さ.' WHERE character = 'サ';
UPDATE japanese_characters SET "mnemonicHint" = 'Three short strokes like falling rain — ''shi'' for a light shower.' WHERE character = 'シ';
UPDATE japanese_characters SET "mnemonicHint" = 'A person crouching in a swirl — ''su'' for a sumo stance.' WHERE character = 'ス';
UPDATE japanese_characters SET "mnemonicHint" = 'A squared-off seesaw, angular version of せ.' WHERE character = 'セ';
UPDATE japanese_characters SET "mnemonicHint" = 'Two strokes like a falling drop — mirror image of ツ.' WHERE character = 'ソ';
UPDATE japanese_characters SET "mnemonicHint" = 'A standing figure, angular version of た shouting ''ta-da!''' WHERE character = 'タ';
UPDATE japanese_characters SET "mnemonicHint" = 'A ''T'' shape with a hook, angular version of ち.' WHERE character = 'チ';
UPDATE japanese_characters SET "mnemonicHint" = 'Three short strokes like a cresting wave — mirror image of ソ.' WHERE character = 'ツ';
UPDATE japanese_characters SET "mnemonicHint" = 'A television antenna on a stand — ''te'' for ''TV''.' WHERE character = 'テ';
UPDATE japanese_characters SET "mnemonicHint" = 'A simple hook, angular version of と — ''to'' for ''toe''.' WHERE character = 'ト';
UPDATE japanese_characters SET "mnemonicHint" = 'A cross shape, angular version of な.' WHERE character = 'ナ';
UPDATE japanese_characters SET "mnemonicHint" = 'Two horizontal strokes, like the kanji for ''two'' — ''ni'' for ''knee-two''.' WHERE character = 'ニ';
UPDATE japanese_characters SET "mnemonicHint" = 'A noodle looping with a tail, angular version of ぬ.' WHERE character = 'ヌ';
UPDATE japanese_characters SET "mnemonicHint" = 'A shrine gate shape — ''ne'' resembles ネ used in shrine names.' WHERE character = 'ネ';
UPDATE japanese_characters SET "mnemonicHint" = 'A single downward slash — the simplest katakana, just one stroke.' WHERE character = 'ノ';
UPDATE japanese_characters SET "mnemonicHint" = 'Two legs standing apart, like a person laughing ''ha ha''.' WHERE character = 'ハ';
UPDATE japanese_characters SET "mnemonicHint" = 'A simple hook and line, angular version of ひ.' WHERE character = 'ヒ';
UPDATE japanese_characters SET "mnemonicHint" = 'A single hook stroke like a sickle — ''fu'' for the hook.' WHERE character = 'フ';
UPDATE japanese_characters SET "mnemonicHint" = 'A small peak or hill — same shape as へ in hiragana.' WHERE character = 'ヘ';
UPDATE japanese_characters SET "mnemonicHint" = 'A house with a crossbeam — angular ''home''.' WHERE character = 'ホ';
UPDATE japanese_characters SET "mnemonicHint" = 'A hook with a cross stroke, angular version of ま.' WHERE character = 'マ';
UPDATE japanese_characters SET "mnemonicHint" = 'Three short strokes like a cat''s whiskers — ''mi'' for whiskers.' WHERE character = 'ミ';
UPDATE japanese_characters SET "mnemonicHint" = 'A cow''s face, angular version — ''mu'' sounds like ''moo''.' WHERE character = 'ム';
UPDATE japanese_characters SET "mnemonicHint" = 'A crossed ''X'' shape, angular version of め — ''me'' means ''eye''.' WHERE character = 'メ';
UPDATE japanese_characters SET "mnemonicHint" = 'A fishhook with a crossbar, angular version of も.' WHERE character = 'モ';
UPDATE japanese_characters SET "mnemonicHint" = 'A slingshot ''Y'' shape, angular version of や.' WHERE character = 'ヤ';
UPDATE japanese_characters SET "mnemonicHint" = 'A hook with a loop, angular version of ゆ.' WHERE character = 'ユ';
UPDATE japanese_characters SET "mnemonicHint" = 'Three horizontal strokes like a flag on a pole — ''yo!'' waving.' WHERE character = 'ヨ';
UPDATE japanese_characters SET "mnemonicHint" = 'A hook with a short leg, angular version of ら.' WHERE character = 'ラ';
UPDATE japanese_characters SET "mnemonicHint" = 'Two vertical strokes like chopsticks, angular version of り.' WHERE character = 'リ';
UPDATE japanese_characters SET "mnemonicHint" = 'A hook with a swirling tail, angular version of る.' WHERE character = 'ル';
UPDATE japanese_characters SET "mnemonicHint" = 'A single swooping stroke like a ramp — ''re'' for a ramp.' WHERE character = 'レ';
UPDATE japanese_characters SET "mnemonicHint" = 'A perfect square, like a rolled-up box — ''ro'' for a box.' WHERE character = 'ロ';
UPDATE japanese_characters SET "mnemonicHint" = 'A hook with a small tail, angular version of わ.' WHERE character = 'ワ';
UPDATE japanese_characters SET "mnemonicHint" = 'Rare — a hook with a flourish, only used as the particle ''wo/o''.' WHERE character = 'ヲ';
UPDATE japanese_characters SET "mnemonicHint" = 'Two short strokes like a check mark — the only ''n'' sound, quick and sharp.' WHERE character = 'ン';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as カ (ka) plus dakuten marks (゛) — buzzes into ''ga''.' WHERE character = 'ガ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as キ (ki) plus dakuten marks — buzzes into ''gi''.' WHERE character = 'ギ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ク (ku) plus dakuten marks — buzzes into ''gu''.' WHERE character = 'グ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ケ (ke) plus dakuten marks — buzzes into ''ge''.' WHERE character = 'ゲ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as コ (ko) plus dakuten marks — buzzes into ''go''.' WHERE character = 'ゴ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as サ (sa) plus dakuten marks — buzzes into ''za''.' WHERE character = 'ザ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as シ (shi) plus dakuten marks — buzzes into ''ji''.' WHERE character = 'ジ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ス (su) plus dakuten marks — buzzes into ''zu''.' WHERE character = 'ズ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as セ (se) plus dakuten marks — buzzes into ''ze''.' WHERE character = 'ゼ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ソ (so) plus dakuten marks — buzzes into ''zo''.' WHERE character = 'ゾ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as タ (ta) plus dakuten marks — buzzes into ''da''.' WHERE character = 'ダ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as テ (te) plus dakuten marks — buzzes into ''de''.' WHERE character = 'デ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ト (to) plus dakuten marks — buzzes into ''do''.' WHERE character = 'ド';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ハ (ha) plus dakuten marks — buzzes into ''ba''.' WHERE character = 'バ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ヒ (hi) plus dakuten marks — buzzes into ''bi''.' WHERE character = 'ビ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as フ (fu) plus dakuten marks — buzzes into ''bu''.' WHERE character = 'ブ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ヘ (he) plus dakuten marks — buzzes into ''be''.' WHERE character = 'ベ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ホ (ho) plus dakuten marks — buzzes into ''bo''.' WHERE character = 'ボ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ハ (ha) with a small circle (゜) — pops crisply into ''pa''.' WHERE character = 'パ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ヒ (hi) with a small circle (゜) — pops into ''pi''.' WHERE character = 'ピ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as フ (fu) with a small circle (゜) — pops into ''pu''.' WHERE character = 'プ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ヘ (he) with a small circle (゜) — pops into ''pe''.' WHERE character = 'ペ';
UPDATE japanese_characters SET "mnemonicHint" = 'Same as ホ (ho) with a small circle (゜) — pops into ''po''.' WHERE character = 'ポ';
