-- Run this in the Supabase SQL Editor to populate mnemonic hints.
-- Hiragana
UPDATE japanese_characters SET "mnemonicHint" = 'Ahh! — Looks like someone opening their mouth wide, exclaiming ''Ahh!'' The shape has an open mouth at the bottom.' WHERE character = 'あ';
UPDATE japanese_characters SET "mnemonicHint" = 'Eels — Two eels swimming side by side. They squirm and squeak ''eee!'' Picture them wriggling next to each other.' WHERE character = 'い';
UPDATE japanese_characters SET "mnemonicHint" = 'Oooh — A little whistle shape. Pucker your lips into a circle and blow ''ooo!'' The curved top is your puckered lips.' WHERE character = 'う';
UPDATE japanese_characters SET "mnemonicHint" = 'Eh? — A surprised person throwing their arms up saying ''Eh?!'' The crossing strokes look like arms flung wide in surprise.' WHERE character = 'え';
UPDATE japanese_characters SET "mnemonicHint" = 'Oh! — An octopus reaching a tentacle out, saying ''Oh!'' The long bottom stroke is the tentacle stretching out.' WHERE character = 'お';
UPDATE japanese_characters SET "mnemonicHint" = 'Car — Looks like a stick figure sitting in a car with arms up. ''Ka-vroom!'' The vertical line is the driver, the curved arm is the wheel.' WHERE character = 'か';
UPDATE japanese_characters SET "mnemonicHint" = 'Key — A fancy old key with prongs sticking out. ''Keep the kee-y!'' The horizontal lines are the teeth of the key.' WHERE character = 'き';
UPDATE japanese_characters SET "mnemonicHint" = 'Cuckoo bird — An open bird beak pointing right, saying ''coo!'' Picture a cuckoo clock beak swinging open.' WHERE character = 'く';
UPDATE japanese_characters SET "mnemonicHint" = 'Kettle — A kettle with a spout and handle. ''Keh... this kettle is hot!'' The vertical stroke is the body, the top is the spout.' WHERE character = 'け';
UPDATE japanese_characters SET "mnemonicHint" = 'Coil — Two lines stacked like coiled rope on the floor. ''Ko-il it up!'' Imagine two loops of rope lying flat.' WHERE character = 'こ';
UPDATE japanese_characters SET "mnemonicHint" = 'Samurai — Crossed blades of a samurai''s sword. ''Sa-murai slice!'' The crossing strokes look like two swords crossing in battle.' WHERE character = 'さ';
UPDATE japanese_characters SET "mnemonicHint" = 'She — A fishhook curving like the letter J. ''A shiny fishhook!'' Picture a gleaming hook ready to catch a fish.' WHERE character = 'し';
UPDATE japanese_characters SET "mnemonicHint" = 'Sushi — A swirling sushi roll with a tail. ''Su-shi spins around!'' Imagine a California roll spinning on a conveyor belt.' WHERE character = 'す';
UPDATE japanese_characters SET "mnemonicHint" = 'Set — A person setting something on a table, arms akimbo. ''Say... sit down and set the table!'' The bottom stroke is the table surface.' WHERE character = 'せ';
UPDATE japanese_characters SET "mnemonicHint" = 'Soccer — A leg kicking a soccer ball powerfully. ''So powerful!'' The curving stroke is the leg mid-kick.' WHERE character = 'そ';
UPDATE japanese_characters SET "mnemonicHint" = 'Table — A table with sturdy legs underneath. ''Ta-ble time!'' The horizontal lines are the tabletop and the strokes below are the legs.' WHERE character = 'た';
UPDATE japanese_characters SET "mnemonicHint" = 'Cheerful dog — A chihuahua sitting up alert. ''Chee-ky little dog!'' The curved top is its perky ears, the stroke below is its sitting body.' WHERE character = 'ち';
UPDATE japanese_characters SET "mnemonicHint" = 'Tsunami — A rolling wave curling over itself. ''Tsu-nami!'' The wide curving shape is a wave building before it crashes.' WHERE character = 'つ';
UPDATE japanese_characters SET "mnemonicHint" = 'Tea — A teacup handle. ''Teh... have some tea!'' The hook at the bottom is the handle you grip when sipping.' WHERE character = 'て';
UPDATE japanese_characters SET "mnemonicHint" = 'Toe — A big toe sticking up with a tiny nail on top. ''To-e!'' The vertical stroke is the toe, the small hook at top is the toenail.' WHERE character = 'と';
UPDATE japanese_characters SET "mnemonicHint" = 'Nap — A person taking a nap, head drooping forward. Picture someone dozing off at their desk, head bent over their arms.' WHERE character = 'な';
UPDATE japanese_characters SET "mnemonicHint" = 'Needle — Two sharp, parallel needle strokes. ''Knee-dle sharp!'' The two lines are a needle''s sharp body, ready to sew.' WHERE character = 'に';
UPDATE japanese_characters SET "mnemonicHint" = 'Noodles — A swirly, loopy noodle shape. ''Noo-dles in a bowl!'' The curving loop looks like a noodle swirling in broth.' WHERE character = 'ぬ';
UPDATE japanese_characters SET "mnemonicHint" = 'Necktie — A flowing necktie hanging down with a knot at top. ''Tie your ne-cktie!'' The shape traces from the knot down to the pointed tip.' WHERE character = 'ね';
UPDATE japanese_characters SET "mnemonicHint" = 'No! — A swirling vortex like a spinning ''NO'' sign. ''Just say no!'' The round spiral is emphatic — a firm, final no.' WHERE character = 'の';
UPDATE japanese_characters SET "mnemonicHint" = 'Ha-ha — A laughing person with arms thrown wide. ''Ha ha ha!'' The three main strokes are a body, outstretched arms, and the laughter itself.' WHERE character = 'は';
UPDATE japanese_characters SET "mnemonicHint" = 'Heel — A foot with a high heel curving behind it. ''Hee hee hee!'' The long curved stroke is the elegant arch of a high-heeled shoe.' WHERE character = 'ひ';
UPDATE japanese_characters SET "mnemonicHint" = 'Funny face — Two bumps on top like a cartoonish smiling face. ''Foo — so funny!'' The top strokes are eyes, the bottom is a wide grin.' WHERE character = 'ふ';
UPDATE japanese_characters SET "mnemonicHint" = 'Heap — A gentle hill or small heap of snow. ''Heh, what a heap!'' The single peaked stroke is a mound rising and falling gently.' WHERE character = 'へ';
UPDATE japanese_characters SET "mnemonicHint" = 'Ho-ho — Santa''s round belly with a belt. ''Ho ho ho!'' The shape with its center line looks just like Santa''s jolly round belly.' WHERE character = 'ほ';
UPDATE japanese_characters SET "mnemonicHint" = 'Mama — A nurturing mama with arms curved around a baby. The horizontal lines are her embrace, the vertical stroke is the baby she holds.' WHERE character = 'ま';
UPDATE japanese_characters SET "mnemonicHint" = 'Meander — Two strokes meandering like a winding river. ''Mee-ander!'' Picture a river snaking lazily through a valley.' WHERE character = 'み';
UPDATE japanese_characters SET "mnemonicHint" = 'Moo — A cow''s face with a horn poking up. ''Moo!'' The curving top is the horn, and the loop at the bottom is the cow''s nose.' WHERE character = 'む';
UPDATE japanese_characters SET "mnemonicHint" = 'Medusa — Swirling snakes like Medusa''s tangled hair. ''Meh-dusa!'' The looping, intertwined strokes are her writhing serpent locks.' WHERE character = 'め';
UPDATE japanese_characters SET "mnemonicHint" = 'More hooks — A fishhook with extra notches for catching more fish. ''Mo-re fish!'' Two hooks crossed over a line for maximum catching power.' WHERE character = 'も';
UPDATE japanese_characters SET "mnemonicHint" = 'Yacht — A small sailboat seen from the side. ''Yah, let''s sail!'' The angled stroke is the sail, the bottom line is the hull on the water.' WHERE character = 'や';
UPDATE japanese_characters SET "mnemonicHint" = 'Yummy — A spoon dipping into a bowl of soup. ''Yoo-mm-y!'' The curved top is the spoon bowl, the vertical stroke goes into the soup.' WHERE character = 'ゆ';
UPDATE japanese_characters SET "mnemonicHint" = 'Yo-yo — A yo-yo bouncing on a string. ''Yo!'' The open top is the yo-yo, and the looping stroke below is the string in motion.' WHERE character = 'よ';
UPDATE japanese_characters SET "mnemonicHint" = 'Rabbit — A rabbit sitting with one ear perked up. ''Rah!'' The curved top stroke is the ear, and the bottom loop is the rabbit''s body.' WHERE character = 'ら';
UPDATE japanese_characters SET "mnemonicHint" = 'Reeds — Two tall reeds growing from the ground by a river. ''Ree-ds!'' The two vertical strokes stand tall like reeds in the breeze.' WHERE character = 'り';
UPDATE japanese_characters SET "mnemonicHint" = 'Rooster — A rooster''s curly tail feather. ''Roo-doo-doo!'' The long curling stroke is the rooster''s proud, spiraling tail plume.' WHERE character = 'る';
UPDATE japanese_characters SET "mnemonicHint" = 'Reindeer — A reindeer kicking up its hind leg. ''Reh-indeer!'' The main stroke flows down and the kicked-up leg curls back.' WHERE character = 'れ';
UPDATE japanese_characters SET "mnemonicHint" = 'Rope — A coiled rope spiral (like る without the tail). ''Row row row your boat!'' The looping stroke is a length of rope coiled on the deck.' WHERE character = 'ろ';
UPDATE japanese_characters SET "mnemonicHint" = 'Water — A water swirl flowing gently around a stone. ''Wah!'' The curved stroke with a loop traces the gentle eddy of flowing water.' WHERE character = 'わ';
UPDATE japanese_characters SET "mnemonicHint" = 'Whoa — Like は (ha) but with an extra stroke showing great effort. ''Whoa — so much work!'' This rarely-used particle takes real effort to write.' WHERE character = 'を';
UPDATE japanese_characters SET "mnemonicHint" = 'Nun — A nun bowing her head in quiet prayer. The curved stroke bends forward like a devout nun with head lowered.' WHERE character = 'ん';
UPDATE japanese_characters SET "mnemonicHint" = 'Garlic — か (ka) with a stinky dakuten mark. The two little ticks are wafts of garlic smell. ''Ga-rlic breath!''' WHERE character = 'が';
UPDATE japanese_characters SET "mnemonicHint" = 'Giraffe — き (ki) with a dakuten. The key grew a long giraffe neck. ''A gee-raffe-shaped key!''' WHERE character = 'ぎ';
UPDATE japanese_characters SET "mnemonicHint" = 'Gooey — く (ku) with a dakuten. The cuckoo beak got gooey! ''Goo-ey beak!''' WHERE character = 'ぐ';
UPDATE japanese_characters SET "mnemonicHint" = 'Get — け (ke) with a dakuten. ''Geh — get that kettle off the stove!''' WHERE character = 'げ';
UPDATE japanese_characters SET "mnemonicHint" = 'Go — こ (ko) with a dakuten. The coiled rope got the signal to go! ''Go go go!''' WHERE character = 'ご';
UPDATE japanese_characters SET "mnemonicHint" = 'Zany — さ (sa) with a dakuten. The samurai went completely zany! ''Za-ny samurai slash!''' WHERE character = 'ざ';
UPDATE japanese_characters SET "mnemonicHint" = 'Jiggle — し (shi) with a dakuten. The fishhook started jiggling in the water. ''Ji-ggle it to catch fish!''' WHERE character = 'じ';
UPDATE japanese_characters SET "mnemonicHint" = 'Zoo — す (su) with a dakuten. A sushi zoo! ''Zu-u full of sushi animals!''' WHERE character = 'ず';
UPDATE japanese_characters SET "mnemonicHint" = 'Zebra — せ (se) with a dakuten. The table has zebra stripes! ''Ze-bra table!''' WHERE character = 'ぜ';
UPDATE japanese_characters SET "mnemonicHint" = 'Zoo kick — そ (so) with a dakuten. A zoo animal kicking its legs. ''Zo-o animal kick!''' WHERE character = 'ぞ';
UPDATE japanese_characters SET "mnemonicHint" = 'Dad — た (ta) with a dakuten. ''Da-d built this table!'' The table got a dad upgrade with two extra marks.' WHERE character = 'だ';
UPDATE japanese_characters SET "mnemonicHint" = 'Jeeze — ち (chi) with a dakuten. This rare character makes you say ''Jee-ze!'' It''s almost never used in modern Japanese.' WHERE character = 'ぢ';
UPDATE japanese_characters SET "mnemonicHint" = 'Buzz — つ (tsu) with a dakuten. The tsunami wave started buzzing! ''Zu-zu-zum, hear the buzz!''' WHERE character = 'づ';
UPDATE japanese_characters SET "mnemonicHint" = 'Deck — て (te) with a dakuten. A teacup sitting on a deck. ''De-ck party with tea!''' WHERE character = 'で';
UPDATE japanese_characters SET "mnemonicHint" = 'Do — と (to) with a dakuten. The toe taps to the beat! ''Do re mi... do!'' Tap your toe in rhythm.' WHERE character = 'ど';
UPDATE japanese_characters SET "mnemonicHint" = 'Bah — は (ha) with a dakuten. The laughter turned into a ''Bah!'' ''Ba-h! Ha turned bad!''' WHERE character = 'ば';
UPDATE japanese_characters SET "mnemonicHint" = 'Bee — ひ (hi) with a dakuten. A bee perched on the high heel! ''Bee on the heel — buzz!''' WHERE character = 'び';
UPDATE japanese_characters SET "mnemonicHint" = 'Bull — ふ (fu) with a dakuten. The funny face became a charging bull! ''Bu-ll charge!''' WHERE character = 'ぶ';
UPDATE japanese_characters SET "mnemonicHint" = 'Be — へ (he) with a dakuten. The heap became a mountain! ''Be a big heap!''' WHERE character = 'べ';
UPDATE japanese_characters SET "mnemonicHint" = 'Bo — ほ (ho) with a dakuten. Santa changed his tune! ''Bo-ho-ho!''' WHERE character = 'ぼ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pa — は (ha) with a handakuten circle. The little circle is a bubble that popped! ''Pa — pop! Pa came home!''' WHERE character = 'ぱ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pi — ひ (hi) with a handakuten circle. A bubble floating above the heel. ''Pi in the sky!''' WHERE character = 'ぴ';
UPDATE japanese_characters SET "mnemonicHint" = 'Puff — ふ (fu) with a handakuten circle. A puff of air from the funny face. ''Pu-ff!'' Blow out the candle.' WHERE character = 'ぷ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pea — へ (he) with a handakuten circle. A pea rolling down the hill! ''Pe-a rolling pe-rfectly!''' WHERE character = 'ぺ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pop — ほ (ho) with a handakuten circle. A bubble popping next to Santa''s belly! ''Po-p goes Santa!''' WHERE character = 'ぽ';

-- Katakana
UPDATE japanese_characters SET "mnemonicHint" = 'Angled A — Like a capital letter A that has been tilted sideways. ''Ah!'' Imagine an A leaning back lazily in a chair.' WHERE character = 'ア';
UPDATE japanese_characters SET "mnemonicHint" = 'Eeling over — A person leaning dramatically with a line keeping them up. ''Ee!'' Picture someone saying ''ee!'' as they tip sideways.' WHERE character = 'イ';
UPDATE japanese_characters SET "mnemonicHint" = 'U with a hat — A U shape wearing a little hat on top. ''Oo!'' Put your hat on and say ''oooh!'' The dot is the hat, the U is the face.' WHERE character = 'ウ';
UPDATE japanese_characters SET "mnemonicHint" = 'Elevator — Like the capital letter H with one arm removed, leaving an elevator shaft. ''Eh — the elevator!'' Ride it up and down.' WHERE character = 'エ';
UPDATE japanese_characters SET "mnemonicHint" = 'Oh! A crossword — Like a plus sign with an extra stroke. ''Oh! A crossword puzzle!'' The crossed lines look like a crossword grid.' WHERE character = 'オ';
UPDATE japanese_characters SET "mnemonicHint" = 'Canoe paddle — A paddle blade with a handle. ''Ka-noe!'' Picture yourself paddling a canoe — the two strokes are the blade and handle.' WHERE character = 'カ';
UPDATE japanese_characters SET "mnemonicHint" = 'Kite frame — Multiple crossing lines like a kite''s structural frame. ''Kee-te flying!'' Imagine the bamboo skeleton of a kite soaring above.' WHERE character = 'キ';
UPDATE japanese_characters SET "mnemonicHint" = 'Cool angle — Like an angle bracket >. ''Coo-l corner!'' A sharp, cool geometric angle pointing to the right.' WHERE character = 'ク';
UPDATE japanese_characters SET "mnemonicHint" = 'Key prongs — A key without a ring, just the serrated prongs. ''Ke-y teeth!'' Picture just the cutting part of a house key.' WHERE character = 'ケ';
UPDATE japanese_characters SET "mnemonicHint" = 'Corner — A right-angle bracket like a sharp corner. ''Ko-rner!'' Two lines meeting at a right angle, like the corner of a room.' WHERE character = 'コ';
UPDATE japanese_characters SET "mnemonicHint" = 'Samurai cap — Three strokes like the outline of a samurai''s helmet. ''Sa-murai!'' The crossed top strokes are the helmet''s crest.' WHERE character = 'サ';
UPDATE japanese_characters SET "mnemonicHint" = 'She-dot-dot — Three dots arranged like '': /'' tilted sideways. ''Shee!'' Three shining drops of water sliding down a surface.' WHERE character = 'シ';
UPDATE japanese_characters SET "mnemonicHint" = 'Subway swirl — Like a backwards question mark going underground. ''Su-bway!'' The curved stroke dips underground like subway tracks.' WHERE character = 'ス';
UPDATE japanese_characters SET "mnemonicHint" = 'Set square — A cross with a swooping base, like a drafter''s set square tool. ''Se-t square!'' Picture an architectural drafting tool.' WHERE character = 'セ';
UPDATE japanese_characters SET "mnemonicHint" = 'Swooping bird — Two strokes like a bird diving from above. ''So-ar!'' Picture a hawk swooping down, two wings cutting through air.' WHERE character = 'ソ';
UPDATE japanese_characters SET "mnemonicHint" = 'Talon — Like a bird''s curved talon gripping a branch. ''Ta-lon!'' The hooked stroke is the sharp claw, the crossing line is the branch.' WHERE character = 'タ';
UPDATE japanese_characters SET "mnemonicHint" = 'Cheerleader — Arms raised in a victory cheer. ''Chee-r!'' The top strokes are raised pompom arms, the bottom is the cheerleader''s feet.' WHERE character = 'チ';
UPDATE japanese_characters SET "mnemonicHint" = 'Tsunami dots — Like シ (shi) rotated sideways with three dots in a row. ''Tsu-nami!'' Both シ and ツ are waves — one horizontal, one vertical.' WHERE character = 'ツ';
UPDATE japanese_characters SET "mnemonicHint" = 'Telephone pole — A cross with a long antenna on top. ''Te-lephone!'' Picture a telephone pole with wires strung across the top.' WHERE character = 'テ';
UPDATE japanese_characters SET "mnemonicHint" = 'Totem pole — A vertical post with a notch or wing cut into it. ''To-tem!'' A totem pole carved with a single outstretched wing.' WHERE character = 'ト';
UPDATE japanese_characters SET "mnemonicHint" = 'Nail — A cross with a downward stroke, like hammering a nail. ''Na-il!'' The horizontal line is the hammer blow, the vertical line is the nail.' WHERE character = 'ナ';
UPDATE japanese_characters SET "mnemonicHint" = 'Knees — Two horizontal lines like two bent knees seen from the front. ''Knee! Knee!'' Picture two parallel kneecaps side by side.' WHERE character = 'ニ';
UPDATE japanese_characters SET "mnemonicHint" = 'Nudge — Two crossing strokes like elbowing someone. ''Nu-dge!'' The crossing lines are two people''s elbows making contact.' WHERE character = 'ヌ';
UPDATE japanese_characters SET "mnemonicHint" = 'Necktie — Looks like a necktie hanging down with a knot at top. ''Ne-cktie!'' The shape traces from the Windsor knot down to the pointed tip.' WHERE character = 'ネ';
UPDATE japanese_characters SET "mnemonicHint" = 'No slash — A single diagonal slash, a firm decisive no. ''No!'' Like a red line drawn through something to cancel it.' WHERE character = 'ノ';
UPDATE japanese_characters SET "mnemonicHint" = 'Happy legs — Two legs spread apart in a happy, open stance. ''Ha-ppy!'' Picture someone landing with their legs spread wide, arms up in joy.' WHERE character = 'ハ';
UPDATE japanese_characters SET "mnemonicHint" = 'Heel — Like a backwards F — a foot with a heel jutting back. ''Hi-gh heel!'' Picture the side view of a shoe with a tall heel.' WHERE character = 'ヒ';
UPDATE japanese_characters SET "mnemonicHint" = 'Funny hook — Like a shepherd''s crook or a funny-shaped hook. ''Fu-nny hook!'' A curved hook with a flat top, like a shepherd tending sheep.' WHERE character = 'フ';
UPDATE japanese_characters SET "mnemonicHint" = 'Heap — A small mountain peak — a gentle heap of earth. ''He-ap!'' The single peaked stroke rises and falls like a small hill.' WHERE character = 'ヘ';
UPDATE japanese_characters SET "mnemonicHint" = 'Holy cross — A cross shape with a base. ''Ho-ly!'' Picture a cross in a snowy field during the holidays. ''Ho ho ho!''' WHERE character = 'ホ';
UPDATE japanese_characters SET "mnemonicHint" = 'Mark — Like a checkmark with a hook. ''Ma-rk!'' Make your mark! The angled stroke is a swooping checkmark of approval.' WHERE character = 'マ';
UPDATE japanese_characters SET "mnemonicHint" = 'Me me me — Three horizontal lines like a musical staff. ''Me me me!'' Picture a singer rehearsing scales: ''me me me!''' WHERE character = 'ミ';
UPDATE japanese_characters SET "mnemonicHint" = 'Moo — Like a cow''s lower face — a chin and nose seen from the front. ''Moo!'' The shape is the outline of a cow''s snout.' WHERE character = 'ム';
UPDATE japanese_characters SET "mnemonicHint" = 'Meeting X — An X mark where two paths meet. ''Me-eting point!'' Two lines crossing like roads intersecting at an X.' WHERE character = 'メ';
UPDATE japanese_characters SET "mnemonicHint" = 'More lines — Three horizontal lines with a hook wanting more. ''Mo-re!'' Like a musical staff with an extra note asking for an encore.' WHERE character = 'モ';
UPDATE japanese_characters SET "mnemonicHint" = 'Yacht sail — Like the sail of a small yacht. ''Yah, let''s sail!'' The angled stroke is a sail billowing in the wind.' WHERE character = 'ヤ';
UPDATE japanese_characters SET "mnemonicHint" = 'Yummy bowl — Like a square bowl with a base — a ramen bowl seen from the side. ''Yoo-mm-y!'' Picture a steaming bowl of noodles.' WHERE character = 'ユ';
UPDATE japanese_characters SET "mnemonicHint" = 'Yo backwards E — Like a capital E facing the wrong way. ''Yo — flip that E!'' Imagine someone yelling ''Yo!'' and flipping the letter E around.' WHERE character = 'ヨ';
UPDATE japanese_characters SET "mnemonicHint" = 'Ramp — Like a leaning pillar with a notch — a skate ramp from the side. ''Ra-mp!'' Picture a skateboard ramp with a flat top platform.' WHERE character = 'ラ';
UPDATE japanese_characters SET "mnemonicHint" = 'Reeds — Two vertical strokes standing tall like reeds. ''Ree-ds!'' Picture two bamboo reeds growing upright by a peaceful stream.' WHERE character = 'リ';
UPDATE japanese_characters SET "mnemonicHint" = 'Rule — Like a ruler or set square with a diagonal. ''Ru-le!'' A carpenter''s square lying flat, used to draw perfectly straight lines.' WHERE character = 'ル';
UPDATE japanese_characters SET "mnemonicHint" = 'Reveal — A simple angle stroke, like a curtain being swept aside. ''Reh-veal!'' One decisive stroke unveiling what was hidden.' WHERE character = 'レ';
UPDATE japanese_characters SET "mnemonicHint" = 'Room — A perfect square — a room seen from above. ''Ro-om!'' Imagine looking down at a bare square room from a bird''s-eye view.' WHERE character = 'ロ';
UPDATE japanese_characters SET "mnemonicHint" = 'Water drop — Like a water droplet falling. ''Wa-ter!'' The curved top is the rounded head of a drop, the point is where it falls.' WHERE character = 'ワ';
UPDATE japanese_characters SET "mnemonicHint" = 'Work hard — Like ロ (room) but with extra effort strokes added. ''Wo-rk!'' This rare particle shows extra dedication — more strokes, more work.' WHERE character = 'ヲ';
UPDATE japanese_characters SET "mnemonicHint" = 'Night check — An upward checkmark, like checking something off at night. ''N for night!'' Different from ソ (so) — this one tilts up, like raising your hand.' WHERE character = 'ン';
UPDATE japanese_characters SET "mnemonicHint" = 'Garlic カ — カ (ka) with a stinky dakuten. Two tiny marks are wafts of garlic aroma floating off the paddle. ''Ga-rlic canoe!''' WHERE character = 'ガ';
UPDATE japanese_characters SET "mnemonicHint" = 'Giant kite — キ (ki) with a dakuten. The kite grew giant and voiced! ''Gi-ant kee-te flying high!''' WHERE character = 'ギ';
UPDATE japanese_characters SET "mnemonicHint" = 'Gooey angle — ク (ku) with a dakuten. The cool angle got all gooey! ''Goo-ey corner!''' WHERE character = 'グ';
UPDATE japanese_characters SET "mnemonicHint" = 'Get the key — ケ (ke) with a dakuten. ''Geh — get those key prongs!'' The marks are urgent signals to grab the key.' WHERE character = 'ゲ';
UPDATE japanese_characters SET "mnemonicHint" = 'Go around the corner — コ (ko) with a dakuten. ''Go! Turn the corner now!''' WHERE character = 'ゴ';
UPDATE japanese_characters SET "mnemonicHint" = 'Zany samurai — サ (sa) with a dakuten. The samurai went zany! ''Za-ny helmet warrior!''' WHERE character = 'ザ';
UPDATE japanese_characters SET "mnemonicHint" = 'Jingly dots — シ (shi) with a dakuten. The three dots started jingling! ''Ji-ngle jingle!''' WHERE character = 'ジ';
UPDATE japanese_characters SET "mnemonicHint" = 'Zoo underground — ス (su) with a dakuten. The subway became a zoo! ''Zu-oo underground!''' WHERE character = 'ズ';
UPDATE japanese_characters SET "mnemonicHint" = 'Zebra square — セ (se) with a dakuten. The set square has zebra stripes! ''Ze-bra lines!''' WHERE character = 'ゼ';
UPDATE japanese_characters SET "mnemonicHint" = 'Zooming bird — ソ (so) with a dakuten. The diving bird zooms even faster! ''Zo-om!''' WHERE character = 'ゾ';
UPDATE japanese_characters SET "mnemonicHint" = 'Dad''s talon — タ (ta) with a dakuten. ''Da-d grabbed it with his talon!''' WHERE character = 'ダ';
UPDATE japanese_characters SET "mnemonicHint" = 'Decorated pole — テ (te) with a dakuten. The telephone pole got decorated! ''De-corated te-lephone!''' WHERE character = 'デ';
UPDATE japanese_characters SET "mnemonicHint" = 'Door of the totem — ト (to) with a dakuten. ''Do-or in the totem pole!'' A door cut into the totem.' WHERE character = 'ド';
UPDATE japanese_characters SET "mnemonicHint" = 'Bang — ハ (ha) with a dakuten. The happy legs got a bang! ''Ba-ng! Happy legs explode!''' WHERE character = 'バ';
UPDATE japanese_characters SET "mnemonicHint" = 'Bee on the heel — ヒ (hi) with a dakuten. A bee stung the high heel! ''Bi-te! Bee!''' WHERE character = 'ビ';
UPDATE japanese_characters SET "mnemonicHint" = 'Bull hook — フ (fu) with a dakuten. The funny hook became a bull''s horn! ''Bu-ll charge!''' WHERE character = 'ブ';
UPDATE japanese_characters SET "mnemonicHint" = 'Big heap — ヘ (he) with a dakuten. The heap grew bigger! ''Be a big heap!''' WHERE character = 'ベ';
UPDATE japanese_characters SET "mnemonicHint" = 'Bold cross — ホ (ho) with a dakuten. The holy cross got bold! ''Bo-ld and holy!''' WHERE character = 'ボ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pa pop — ハ (ha) with a handakuten circle. The little circle is a soap bubble that goes pop! ''Pa — pop! Pa came home!''' WHERE character = 'パ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pi bubble — ヒ (hi) with a handakuten circle. A bubble floating above the heel like a pi symbol. ''Pi in the sky!''' WHERE character = 'ピ';
UPDATE japanese_characters SET "mnemonicHint" = 'Puff hook — フ (fu) with a handakuten circle. A puff of air blowing out of the funny hook. ''Pu-ff!''' WHERE character = 'プ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pea on the peak — ヘ (he) with a handakuten circle. A little pea balancing on top of the mountain peak. ''Pe-a on top!''' WHERE character = 'ペ';
UPDATE japanese_characters SET "mnemonicHint" = 'Pop the cross — ホ (ho) with a handakuten circle. A bubble popping next to the holy cross. ''Po-p goes the bubble!''' WHERE character = 'ポ';
